FROM openjdk:8u212-jdk-alpine
RUN apk add --update bash libstdc++ curl zip vim && \
    rm -rf /var/cache/apk/*
# Workaround  https://issues.apache.org/jira/browse/GROOVY-7906 and other 'busybox' related issues.
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
# Install groovy
# Use curl -L to follow redirects
# Also, use sed to make a workaround for https://issues.apache.org/jira/browse/GROOVY-7906
RUN curl -L https://bintray.com/artifact/download/groovy/maven/apache-groovy-binary-2.4.8.zip -o /tmp/groovy.zip && \
    cd /usr/local && \
    unzip /tmp/groovy.zip && \
    rm /tmp/groovy.zip && \
    ln -s /usr/local/groovy-2.4.8 groovy && \
    /usr/local/groovy/bin/groovy -v && \
    cd /usr/local/bin && \
    ln -s /usr/local/groovy/bin/groovy groovy
RUN mkdir /home/groovy
RUN mkdir /home/groovy/scripts 
WORKDIR /home/groovy/scripts
COPY Cluster.groovy .
COPY Hotswap.groovy .
CMD [ "groovy", "Cluster" ]
