FROM envoyproxy/envoy-dev:latest

RUN apt-get update && apt-get -q install -y curl vim python

ADD ./hot-restarter.py /usr/local/bin/hot-restart.py
ADD ./start-envoy.sh /usr/local/bin/start-envoy.sh
ADD ./run.sh /usr/local/bin/run.sh

RUN chmod u+x /usr/local/bin/start-envoy.sh
RUN chmod u+x /usr/local/bin/run.sh

ENTRYPOINT /usr/local/bin/run.sh
